import {APIAdminListDevices as OriginAPIAdminListDevices} from'./APIAdminListDevices';
import {APIAdminListRuns as OriginAPIAdminListRuns} from'./APIAdminListRuns';
import {APIAdminListServices as OriginAPIAdminListServices} from'./APIAdminListServices';
import {APIAdminListStatistics as OriginAPIAdminListStatistics} from'./APIAdminListStatistics';
import {APIAdminResource as OriginAPIAdminResource} from'./APIAdminResource';
import {APIAdminResourceAccount as OriginAPIAdminResourceAccount} from'./APIAdminResourceAccount';
import {APIAdminResourceAccountService as OriginAPIAdminResourceAccountService} from'./APIAdminResourceAccountService';
import {APIAdminResourceCluster as OriginAPIAdminResourceCluster} from'./APIAdminResourceCluster';
import {APIAdminResourceDevice as OriginAPIAdminResourceDevice} from'./APIAdminResourceDevice';
import {APIAdminResourceDeviceModel as OriginAPIAdminResourceDeviceModel} from'./APIAdminResourceDeviceModel';
import {APIAdminResourceDeviceSession as OriginAPIAdminResourceDeviceSession} from'./APIAdminResourceDeviceSession';
import {APIAdminResourceDeviceSessionStandalone as OriginAPIAdminResourceDeviceSessionStandalone} from'./APIAdminResourceDeviceSessionStandalone';
import {APIAdminResourceDeviceTime as OriginAPIAdminResourceDeviceTime} from'./APIAdminResourceDeviceTime';
import {APIAdminResourceFramework as OriginAPIAdminResourceFramework} from'./APIAdminResourceFramework';
import {APIAdminResourceLicense as OriginAPIAdminResourceLicense} from'./APIAdminResourceLicense';
import {APIAdminResourceRun as OriginAPIAdminResourceRun} from'./APIAdminResourceRun';
import {APIAdminResourceRunStandalone as OriginAPIAdminResourceRunStandalone} from'./APIAdminResourceRunStandalone';
import {APIAdminResourceService as OriginAPIAdminResourceService} from'./APIAdminResourceService';
import {APIAdminResourceUser as OriginAPIAdminResourceUser} from'./APIAdminResourceUser';
import {APIAdminResourceUserAccount as OriginAPIAdminResourceUserAccount} from'./APIAdminResourceUserAccount';

export type APIAdminListDevices = InstanceType<typeof OriginAPIAdminListDevices>;
export type APIAdminListRuns = InstanceType<typeof OriginAPIAdminListRuns>;
export type APIAdminListServices = InstanceType<typeof OriginAPIAdminListServices>;
export type APIAdminListStatistics = InstanceType<typeof OriginAPIAdminListStatistics>;
export type APIAdminResource = InstanceType<typeof OriginAPIAdminResource>;
export type APIAdminResourceAccount = InstanceType<typeof OriginAPIAdminResourceAccount>;
export type APIAdminResourceAccountService = InstanceType<typeof OriginAPIAdminResourceAccountService>;
export type APIAdminResourceCluster = InstanceType<typeof OriginAPIAdminResourceCluster>;
export type APIAdminResourceDevice = InstanceType<typeof OriginAPIAdminResourceDevice>;
export type APIAdminResourceDeviceModel = InstanceType<typeof OriginAPIAdminResourceDeviceModel>;
export type APIAdminResourceDeviceSession = InstanceType<typeof OriginAPIAdminResourceDeviceSession>;
export type APIAdminResourceDeviceSessionStandalone = InstanceType<typeof OriginAPIAdminResourceDeviceSessionStandalone>;
export type APIAdminResourceDeviceTime = InstanceType<typeof OriginAPIAdminResourceDeviceTime>;
export type APIAdminResourceFramework = InstanceType<typeof OriginAPIAdminResourceFramework>;
export type APIAdminResourceLicense = InstanceType<typeof OriginAPIAdminResourceLicense>;
export type APIAdminResourceRun = InstanceType<typeof OriginAPIAdminResourceRun>;
export type APIAdminResourceRunStandalone = InstanceType<typeof OriginAPIAdminResourceRunStandalone>;
export type APIAdminResourceService = InstanceType<typeof OriginAPIAdminResourceService>;
export type APIAdminResourceUser = InstanceType<typeof OriginAPIAdminResourceUser>;
export type APIAdminResourceUserAccount = InstanceType<typeof OriginAPIAdminResourceUserAccount>;
